### ISSUE TITLE
Instructions in Wiki don't work as expected

### ISSUE THREAD

**Issue by 9oelM** [as2d/as2d#5]
I wanted to try out on my own without using as2d-example repo.
Two problems I faced:

1. `ERROR: Import file '~lib/as2d/assembly/index.ts' not found.`
```bash
(base) ➜  as2d-simple-example npm run asbuild

> as2d-simple-example@1.0.0 asbuild /Users/jm/Documents/Code/as2d-simple-example
> npm run asbuild:untouched && npm run asbuild:optimized


> as2d-simple-example@1.0.0 asbuild:untouched /Users/jm/Documents/Code/as2d-simple-example
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug

ERROR: Import file '~lib/as2d/assembly/index.ts' not found.
    at parseBacklog (/Users/jm/Documents/Code/as2d-simple-example/node_modules/assemblyscript/cli/asc.js:397:34)
    at Object.main (/Users/jm/Documents/Code/as2d-simple-example/node_modules/assemblyscript/cli/asc.js:450:16)
    at Object.<anonymous> (/Users/jm/Documents/Code/as2d-simple-example/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```
I suspect this is also related to path resolution in AssemblyScript. But I think @jtenner might be able to give an idea on what's happening. That's why I'm filing an issue here.

This simply worked after I changed
```ts
import { getContextById, CanvasRenderingContext2D } from "as2d/assembly/index";
```
to 
```ts
import { getContextById, CanvasRenderingContext2D } from "../node_modules/as2d/assembly/index";
```
Why can AssemblyScript not resolve the path correctly?

2. `AS2DGlue.ts:105 Uncaught (in promise) TypeError: this.wasm.__use_context is not a function`
![image](https://user-images.githubusercontent.com/22465806/69477784-d3ec0900-0e2d-11ea-856e-af676856534b.png)

Now `asbuild` command works, but when parcel builds the project, this error is emitted.
I inspected the code and there is even a test on checking if `__use_context` exists:
https://github.com/as2d/as2d/blob/b22fb7e1544ee02362b686b1cf7d12fff56f0c53/__tests__/glue.ts#L38

But still, the browser complains. Something must be wrong with `wasm` object, because [as2d-example](https://github.com/as2d/as2d-example) repo still uses `useContext` but it works without emitting this error.

What could be the problem?

And by the way, I had to make some modifications to `src/index.ts` to perfect typings:

```ts
// this is a shallow wrapper for the assemblyscript loader
import { instantiateStreaming } from "as2d";
const fs = require('fs');

import { initFunction, updateFunction } from '../assembly';

interface Wasm {
  init: initFunction;
  update: updateFunction;
  useContext(name: string, ctx: CanvasRenderingContext2D): number;
}

(async () => {
  if (!(window as any).Buffer) (window as any).Buffer = require("buffer").Buffer;
  // parcel will inline the module here
  const buffer: Buffer = fs.readFileSync("./build/optimized.wasm");
  const blob: Blob = new Blob([buffer], { type: "application/wasm" });
  const url: string = URL.createObjectURL(blob);
  
  // define your imports here
  const imports = {};
  const wasm: Wasm = await instantiateStreaming(fetch(url), imports);

  const canvas: HTMLCanvasElement = document.querySelector("#as2d");
  const ctx: CanvasRenderingContext2D = canvas.getContext("2d");
  
  // notify web assembly to manage this context
  wasm.useContext('main', ctx);
  
  // once the context is used, the internal `getContextById()` function should now work
  wasm.init(); // this is the web assemly function we exported
  
  // use an update function to draw to the screen
  wasm.update();
})()

```

and `assembly/index.ts`:

```ts
import { getContextById, CanvasRenderingContext2D } from "../node_modules/as2d/assembly/index";

let ctx: CanvasRenderingContext2D | null;

export type initFunction = () => void;

export const init: initFunction = () => {
  ctx = getContextById('main');
}

export type updateFunction = () => void;

export function update(): void {
  if (ctx === null) { return; } // the context should be initialized
  ctx.clearRect(0, 0, 800, 600);
  ctx.fillText("Hello world!", 200, 200);
  ctx.commit(); // always remember to commit, or you will cause a memory leak
}
```

So...
I feel a need to update wiki. And how do you plan on documenting things in the future?

**Comment by jtenner** [comment]
Hey. Thanks for opening the issue!

I promise to take a look at this soon. Any help with pull requests and comments about the software are very much appreciated.

**Comment by jtenner** [comment]
First. I am pretty sure that it should just be in AssemblyScript:

```ts
import {} from "as2d"; // that's it. 
```

Module resolution for AssemblyScript looks in the `as2d` folder in your `node_modules`, then traverses the `assembly` automatically so you don't need to specify it. That's why the example currently doesn't work. I will work on this immediately.

**Comment by AnyThund** [comment]
Hi, I ran into the same problem as @9oelM 's first situation. Then I changed

```
import { getContextById, CanvasRenderingContext2D } from "as2d/assembly/index"
```

to 

```
import { getContextById, CanvasRenderingContext2D } from "../node_modules/as2d/assembly/index"
```

as is suggested above. However, then I got another ERROR attached as following:

```
> asc assembly/index.ts node_modules/as2d/assembly/glue.ts --target debug

ERROR TS2322: Type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D | null' is not assignable to type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D'.

   ctx.fillText("Hello world!", 200, 200);
   ~~~
 in assembly/index.ts(21,3)

ERROR TS2304: Cannot find name '__retain'.

     __retain(pointer);
     ~~~~~~~~
 in node_modules/as2d/assembly/internal/Buffer.ts(276,5)

ERROR TS2322: Type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D | null' is not assignable to type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D'.

   ctx.commit(); // always remember to commit, or you will cause a memory leak
   ~~~
 in assembly/index.ts(22,3)

ERROR TS2304: Cannot find name '__release'.

       __release(load<usize>(pointer + (<usize>i << alignof<usize>())));
       ~~~~~~~~~
 in node_modules/as2d/assembly/internal/Buffer.ts(264,7)

ERROR TS2554: Expected 1 arguments, but got 2.

     let ptr = __alloc(length, idof<ArrayBuffer>());
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in node_modules/as2d/assembly/internal/StackPointer.ts(9,15)

ERROR TS2304: Cannot find name '__retain'.

   __retain(changetype<usize>(defaultBlack));
   ~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(80,3)

ERROR TS2304: Cannot find name '__retain'.

   __retain(changetype<usize>(defaultNone));
   ~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(82,3)

ERROR TS2304: Cannot find name '__retain'.

   __retain(changetype<usize>(defaultFont));
   ~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(84,3)

ERROR TS2304: Cannot find name '__retain'.

   __retain(changetype<usize>(defaultBlack));
   ~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(97,3)

ERROR TS2304: Cannot find name '__retain'.

   __retain(changetype<usize>(defaultShadowColor));
   ~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(98,3)

ERROR TS2554: Expected 1 arguments, but got 2.

   private _currentTransform: ArrayBuffer = changetype<ArrayBuffer>(setArrayBufferIdentity(__alloc(sizeof<f64>() * 6, idof<ArrayBuffer>())));
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(182,91)

ERROR TS2554: Expected 1 arguments, but got 2.

     let ptr = __alloc(length, idof<ArrayBuffer>());
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in node_modules/as2d/assembly/internal/StackPointer.ts(9,15)

ERROR TS2322: Type 'node_modules/as2d/assembly/internal/Buffer/Buffer<i32>' is not assignable to type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D'.

   private _pathStart: StackPointer<Path2DElement> = this._path.decrement();
                                                     ~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(1401,53)

ERROR TS2322: Type 'node_modules/as2d/assembly/internal/Buffer/Buffer<i32>' is not assignable to type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D'.

     changetype<StackPointer<Path2DElement>>(changetype<usize>(this._pathStart) + offsetof<Path2DElement>() * 0x1000);
                                                               ~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(1407,63)

ERROR TS2322: Type 'node_modules/as2d/assembly/internal/Buffer/Buffer<i32>' is not assignable to type 'node_modules/as2d/assembly/renderer/CanvasRenderingContext2D/CanvasRenderingContext2D'.

   private _pathCurrent: StackPointer<Path2DElement> = this._pathStart;
                                                       ~~~~
 in node_modules/as2d/assembly/renderer/CanvasRenderingContext2D.ts(1412,55)

WARNING AS232: Exported generic function or class has no concrete instances.

   export declare function data<T>(size: T, align?: i32): usize;
                           ~~~~
 in ~lib/memory.ts(67,27)

FAILURE 15 compile error(s)
```

What is going on?
